services:
  eworkshop-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: eworkshop-sql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: "Developer"
    volumes:
      - sql_data:/var/opt/mssql
    ports:
      - "${SQL_PORT}:1433"
    networks:
      - eworkshop
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -Q \"SELECT 1\" -b -o /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  eworkshop-api:
    container_name: eworkshop-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./eWorkshop/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      ConnectionStrings__DefaultConnection: "Server=eworkshop-sql,1433;Database=eWorkshop;User=sa;Password=nIcxa2eGxjk7vY;TrustServerCertificate=True"
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "${API_PORT}:8080"
    depends_on:
      eworkshop-sql:
        condition: service_healthy
    networks:
      - eworkshop

networks:
  eworkshop:
    driver: bridge

volumes:
  sql_data: