services:
#mssql docker
  eworkshop-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks:
      - eworkshop

  eworkshop-ids:
    build:
      context: .
      dockerfile: ./eWorkshop.IdentityServer/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
        - ConnectionStrings__DefaultConnection=Server=eworkshop-sql,1433;Database=190128;User=sa;Password=QWElkj132!;TrustServerCertificate=True
        - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5443:5443
    depends_on:
      - eworkshop-sql
    networks:
      - eworkshop

  eworkshop-rabbitmq:
    container_name: eworkshop-rabbitmq
    image: rabbitmq:3.12.1-management
    restart: unless-stopped
    networks:
      - eworkshop
    ports:
      - 5672:5672
      - 15672:15672



  eworkshop-smtp:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./eWorkshop.MailSender/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=7439
      - ASPNETCORE_Kestrel__Certificates__Default__Password=asad
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certifikat.pfx
    networks:
      - eworkshop 
    ports:
      - 7339:80
      - 7439:443
      - 7539:587
    depends_on:
      - eworkshop-rabbitmq

      
  eworkshop-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./eWorkshop/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      - IdentityServerUrl=http://eworkshop-ids:5443
      - IdentityServerMetaDataUrl=http://eworkshop-ids:5443/.well-known/openid-configuration
      - ConnectionStrings__DefaultConnection=Server=eworkshop-sql,1433;Database=190128;User=sa;Password=QWElkj132!;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7189:7189
    networks:
      - eworkshop
    links:
      - eworkshop-sql
      - eworkshop-ids
    depends_on:
      - eworkshop-sql
      - eworkshop-ids

networks:
  eworkshop:
    driver: bridge