services:
  eworkshop-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: eworkshop-sql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: "Developer"
    volumes:
      - sql_data:/var/opt/mssql
    ports:
      - "${SQL_PORT}:1433"
    networks:
      - eworkshop

  eworkshop-api:
    container_name: eworkshop-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./eWorkshop/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      ConnectionStrings__DefaultConnection: "Server=eworkshop-sql,1433;Database=eWorkshop;User=sa;Password=nIcxa2eGxjk7vY;TrustServerCertificate=True"
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "${API_PORT}:8080"
    depends_on:
      - eworkshop-sql
    networks:
      - eworkshop

networks:
  eworkshop:
    driver: bridge

volumes:
  sql_data: