services:
#mssql docker
  eworkshop-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - ${SQL_PORT}:1433
    networks:
      - eworkshop

  eworkshop-ids:
    build:
      context: .
      dockerfile: ./eWorkshop.IdentityServer/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
        - ConnectionStrings__DefaultConnection=Server=eworkshop-sql,${SQL_PORT};Database=${SQL_DATABASE};User=${SQL_USER};Password=${SA_PASSWORD};TrustServerCertificate=True
        - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - ${IDS_PORT}:5443
    depends_on:
      - eworkshop-sql
    networks:
      - eworkshop

  eworkshop-rabbitmq:
    container_name: eworkshop-rabbitmq
    image: rabbitmq:3.12.1-management
    restart: unless-stopped
    environment:
      - RABBITMQ_USER=${RMQ_USER}
      - RABBITMQ_PW=${RMQ_PASSWORD}
    networks:
      - eworkshop
    ports:
      - ${RMQ_PORT}:5672
      - ${RMQ_ADMIN_PORT}:15672

  eworkshop-smtp:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./eWorkshop.MailSender/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=${SMTP_HTTPS_PORT}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=asad
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certifikat.pfx
      - RabbitMQ:Host=eworkshop-rabbitmq
      - RabbitMQ:Port=${RMQ_PORT}
      - RabbitMQ:User=${RMQ_USER}
      - RabbitMQ:Password=${RMQ_PASSWORD}
      - Mail:FromMail=${FROM_MAIL}
      - Mail:Server=${SMTP_SERVER}
      - Mail:AppPassword=${APP_PASSWORD}
      - Mail:Port=${SMTP_SERVER_PORT}
    networks:
      - eworkshop 
    ports:
      - ${SMTP_PORT}:80
      - ${SMTP_HTTPS_PORT}:443
      - ${SMTP_SERVER_PORT}:587
    depends_on:
      - eworkshop-rabbitmq

      
  eworkshop-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./eWorkshop/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      - IdentityServerUrl=http://eworkshop-ids:5443
      - IdentityServerMetaDataUrl=http://eworkshop-ids:5443/.well-known/openid-configuration
      - ConnectionStrings__DefaultConnection=Server=eworkshop-sql,${SQL_PORT};Database=${SQL_DATABASE};User=${SQL_USER};Password=${SA_PASSWORD};TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - ${API_PORT}:7189
    networks:
      - eworkshop
    links:
      - eworkshop-sql
      - eworkshop-ids
    depends_on:
      - eworkshop-sql
      - eworkshop-ids

networks:
  eworkshop:
    driver: bridge