// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eWorkshop.Services.Database;

#nullable disable

namespace eWorkshop.Services.Migrations
{
    [DbContext(typeof(_190128Context))]
    [Migration("20260530200023_opisservisa")]
    partial class opisservisa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UlogeClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KorisniciClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("KorisniciUloge");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<int>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("eWorkshop.Services.Database.IzvrseniServi", b =>
                {
                    b.Property<int>("IzvrseniServisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IzvrseniServisID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IzvrseniServisId"));

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("date");

                    b.Property<int?>("KomponentaId")
                        .HasColumnType("int")
                        .HasColumnName("KomponentaID");

                    b.Property<string>("KomponentaNaziv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KomponentaTip")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KomponentaVrijednost")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ServisId")
                        .HasColumnType("int")
                        .HasColumnName("ServisID");

                    b.HasKey("IzvrseniServisId");

                    b.HasIndex("KomponentaId");

                    b.HasIndex("ServisId");

                    b.ToTable("IzvrseniServis");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Komponente", b =>
                {
                    b.Property<int>("KomponentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KomponentaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KomponentaId"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Opis")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Tip")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Vrijednost")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("KomponentaId")
                        .HasName("PK_Komponenta");

                    b.ToTable("Komponente", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Korisnici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RadnaJedinica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Korisnici", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Lokacija", b =>
                {
                    b.Property<int>("LokacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LokacijaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LokacijaId"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Opis")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LokacijaId");

                    b.ToTable("Lokacija", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.RadniZadatak", b =>
                {
                    b.Property<int>("RadniZadatakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RadniZadatakID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RadniZadatakId"));

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("date");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StateMachine")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RadniZadatakId");

                    b.ToTable("RadniZadatak", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.RadniZadatakUredjaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RadniZadatakId")
                        .HasColumnType("int");

                    b.Property<int>("UredjajId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("RadniZadatakId");

                    b.HasIndex("UredjajId");

                    b.ToTable("RadniZadatakUredjaj", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Servi", b =>
                {
                    b.Property<int>("ServisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServisID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServisId"));

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("date");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int")
                        .HasColumnName("KorisnikID");

                    b.Property<string>("OpisPrijema")
                        .HasColumnType("text");

                    b.Property<string>("OpisServisa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RadniZadatakId")
                        .HasColumnType("int")
                        .HasColumnName("RadniZadatakID");

                    b.Property<int>("UredjajId")
                        .HasColumnType("int")
                        .HasColumnName("UredjajID");

                    b.HasKey("ServisId")
                        .HasName("PK_ServisID");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("RadniZadatakId");

                    b.HasIndex("UredjajId");

                    b.ToTable("Servi");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.TipUredjaja", b =>
                {
                    b.Property<int>("TipUredjajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TipUredjajaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipUredjajaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TipUredjajaId");

                    b.ToTable("TipUredjaja", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Uloge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Uloge", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Uredjaj", b =>
                {
                    b.Property<int>("UredjajId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UredjajID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UredjajId"));

                    b.Property<int>("EvBroj")
                        .HasColumnType("int");

                    b.Property<string>("GodinaIzvedbe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Koda")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Kuciste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LokacijaId")
                        .HasColumnType("int")
                        .HasColumnName("LokacijaID");

                    b.Property<string>("SerijskiBroj")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TipId")
                        .HasColumnType("int")
                        .HasColumnName("TipID");

                    b.HasKey("UredjajId");

                    b.HasIndex("LokacijaId");

                    b.HasIndex("TipId");

                    b.ToTable("Uredjaj", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.KorisniciUloge", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<int>");

                    b.Property<int?>("KorisniciId")
                        .HasColumnType("int");

                    b.HasIndex("KorisniciId");

                    b.HasDiscriminator().HasValue("KorisniciUloge");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.IzvrseniServi", b =>
                {
                    b.HasOne("eWorkshop.Services.Database.Komponente", "Komponenta")
                        .WithMany("IzvrseniServis")
                        .HasForeignKey("KomponentaId")
                        .HasConstraintName("FK_KomponentaServis");

                    b.HasOne("eWorkshop.Services.Database.Servi", "Servis")
                        .WithMany("IzvrseniServis")
                        .HasForeignKey("ServisId")
                        .HasConstraintName("FK_Servis");

                    b.Navigation("Komponenta");

                    b.Navigation("Servis");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.RadniZadatakUredjaj", b =>
                {
                    b.HasOne("eWorkshop.Services.Database.Korisnici", "Korisnik")
                        .WithMany("RadniZadatakUredjajs")
                        .HasForeignKey("KorisnikId")
                        .HasConstraintName("FK_Korisnik");

                    b.HasOne("eWorkshop.Services.Database.RadniZadatak", "RadniZadatak")
                        .WithMany("RadniZadatakUredjajs")
                        .HasForeignKey("RadniZadatakId")
                        .IsRequired()
                        .HasConstraintName("FK_RadniZadatak");

                    b.HasOne("eWorkshop.Services.Database.Uredjaj", "Uredjaj")
                        .WithMany("RadniZadatakUredjajs")
                        .HasForeignKey("UredjajId")
                        .IsRequired()
                        .HasConstraintName("FK_Uredjaj");

                    b.Navigation("Korisnik");

                    b.Navigation("RadniZadatak");

                    b.Navigation("Uredjaj");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Servi", b =>
                {
                    b.HasOne("eWorkshop.Services.Database.Korisnici", "Korisnik")
                        .WithMany("Servis")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_KorisnikID");

                    b.HasOne("eWorkshop.Services.Database.RadniZadatak", "RadniZadatak")
                        .WithMany("Servis")
                        .HasForeignKey("RadniZadatakId")
                        .IsRequired()
                        .HasConstraintName("FK_RadniZadatakID");

                    b.HasOne("eWorkshop.Services.Database.Uredjaj", "Uredjaj")
                        .WithMany("Servis")
                        .HasForeignKey("UredjajId")
                        .IsRequired()
                        .HasConstraintName("FK_UredjajID");

                    b.Navigation("Korisnik");

                    b.Navigation("RadniZadatak");

                    b.Navigation("Uredjaj");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Uredjaj", b =>
                {
                    b.HasOne("eWorkshop.Services.Database.Lokacija", "Lokacija")
                        .WithMany("Uredjajs")
                        .HasForeignKey("LokacijaId")
                        .HasConstraintName("FK__Uredjaj__Lokacij__45F365D3");

                    b.HasOne("eWorkshop.Services.Database.TipUredjaja", "Tip")
                        .WithMany("Uredjajs")
                        .HasForeignKey("TipId")
                        .IsRequired()
                        .HasConstraintName("FK_UredjajTip");

                    b.Navigation("Lokacija");

                    b.Navigation("Tip");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.KorisniciUloge", b =>
                {
                    b.HasOne("eWorkshop.Services.Database.Korisnici", null)
                        .WithMany("KorisniciUloge")
                        .HasForeignKey("KorisniciId");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Komponente", b =>
                {
                    b.Navigation("IzvrseniServis");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Korisnici", b =>
                {
                    b.Navigation("KorisniciUloge");

                    b.Navigation("RadniZadatakUredjajs");

                    b.Navigation("Servis");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Lokacija", b =>
                {
                    b.Navigation("Uredjajs");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.RadniZadatak", b =>
                {
                    b.Navigation("RadniZadatakUredjajs");

                    b.Navigation("Servis");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Servi", b =>
                {
                    b.Navigation("IzvrseniServis");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.TipUredjaja", b =>
                {
                    b.Navigation("Uredjajs");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Uredjaj", b =>
                {
                    b.Navigation("RadniZadatakUredjajs");

                    b.Navigation("Servis");
                });
#pragma warning restore 612, 618
        }
    }
}
