// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eWorkshop.Services.Database;

#nullable disable

namespace eWorkshop.Services.Migrations
{
    [DbContext(typeof(_190128Context))]
    partial class _190128ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eWorkshop.Services.Database.IzvrseniServi", b =>
                {
                    b.Property<int>("IzvrseniServisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IzvrseniServisID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IzvrseniServisId"));

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("date");

                    b.Property<int?>("KomponentaId")
                        .HasColumnType("int")
                        .HasColumnName("KomponentaID");

                    b.Property<int?>("ServisId")
                        .HasColumnType("int")
                        .HasColumnName("ServisID");

                    b.HasKey("IzvrseniServisId");

                    b.HasIndex("KomponentaId");

                    b.HasIndex("ServisId");

                    b.ToTable("IzvrseniServis");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Klijenti", b =>
                {
                    b.Property<int>("KlijentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KlijentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KlijentId"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ime")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("KorisnickoIme")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LozinkaHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LozinkaSalt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Prezime")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("KlijentId");

                    b.ToTable("Klijenti", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Komponente", b =>
                {
                    b.Property<int>("KomponentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KomponentaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KomponentaId"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Opis")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Tip")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Vrijednost")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("KomponentaId")
                        .HasName("PK_Komponenta");

                    b.ToTable("Komponente", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Korisnici", b =>
                {
                    b.Property<int>("KorisniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KorisniciID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisniciId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LozinkaSalt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("KorisniciId");

                    b.ToTable("Korisnici", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.KorisniciUloge", b =>
                {
                    b.Property<int>("KorisnikUlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KorisnikUlogaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikUlogaId"));

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int")
                        .HasColumnName("KorisnikID");

                    b.Property<int>("UlogaId")
                        .HasColumnType("int")
                        .HasColumnName("UlogaID");

                    b.HasKey("KorisnikUlogaId")
                        .HasName("PK_KorisnikUloga");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("UlogaId");

                    b.ToTable("KorisniciUloge", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Lokacija", b =>
                {
                    b.Property<int>("LokacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LokacijaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LokacijaId"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Opis")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LokacijaId");

                    b.ToTable("Lokacija", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Magacin", b =>
                {
                    b.Property<int>("MagacinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MagacinID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MagacinId"));

                    b.Property<int?>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int?>("KomponentaId")
                        .HasColumnType("int")
                        .HasColumnName("KomponentaID");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Opis")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MagacinId");

                    b.HasIndex("KomponentaId");

                    b.ToTable("Magacin", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.RadniZadatak", b =>
                {
                    b.Property<int>("RadniZadatakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RadniZadatakID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RadniZadatakId"));

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("date");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StateMachine")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RadniZadatakId");

                    b.ToTable("RadniZadatak", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Servi", b =>
                {
                    b.Property<int>("ServisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServisID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServisId"));

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("date");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int")
                        .HasColumnName("KorisnikID");

                    b.Property<string>("Napomena")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RadniZadatakId")
                        .HasColumnType("int")
                        .HasColumnName("RadniZadatakID");

                    b.Property<int>("UredjajId")
                        .HasColumnType("int")
                        .HasColumnName("UredjajID");

                    b.HasKey("ServisId")
                        .HasName("PK_ServisID");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("RadniZadatakId");

                    b.HasIndex("UredjajId");

                    b.ToTable("Servis");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.TipUredjaja", b =>
                {
                    b.Property<int>("TipUredjajaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TipUredjajaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipUredjajaId"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TipUredjajaId");

                    b.ToTable("TipUredjaja", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Ugovor", b =>
                {
                    b.Property<int>("UgovorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UgovorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UgovorId"));

                    b.Property<int?>("Cijena")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("date");

                    b.Property<int>("RadniZadatakId")
                        .HasColumnType("int")
                        .HasColumnName("RadniZadatakID");

                    b.HasKey("UgovorId")
                        .HasName("PK_Uogovor");

                    b.HasIndex("RadniZadatakId");

                    b.ToTable("Ugovor", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Uloge", b =>
                {
                    b.Property<int>("UlogaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UlogaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UlogaId"));

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Opis")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UlogaId")
                        .HasName("PK_Uloga");

                    b.ToTable("Uloge", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Upit", b =>
                {
                    b.Property<int>("UpitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UpitID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UpitId"));

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("date");

                    b.Property<int?>("KlijentId")
                        .HasColumnType("int")
                        .HasColumnName("KlijentID");

                    b.Property<string>("Naslov")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Opis")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UpitId")
                        .HasName("PK_Upis");

                    b.HasIndex("KlijentId");

                    b.ToTable("Upit", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Uredjaj", b =>
                {
                    b.Property<int>("UredjajId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UredjajID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UredjajId"));

                    b.Property<string>("GodinaIzvedbe")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Koda")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("LokacijaId")
                        .HasColumnType("int")
                        .HasColumnName("LokacijaID");

                    b.Property<string>("SerijskiBroj")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TipId")
                        .HasColumnType("int")
                        .HasColumnName("TipID");

                    b.HasKey("UredjajId");

                    b.HasIndex("LokacijaId");

                    b.HasIndex("TipId");

                    b.ToTable("Uredjaj", (string)null);
                });

            modelBuilder.Entity("eWorkshop.Services.Database.IzvrseniServi", b =>
                {
                    b.HasOne("eWorkshop.Services.Database.Komponente", "Komponenta")
                        .WithMany("IzvrseniServis")
                        .HasForeignKey("KomponentaId")
                        .HasConstraintName("FK_KomponentaServis");

                    b.HasOne("eWorkshop.Services.Database.Servi", "Servis")
                        .WithMany("IzvrseniServis")
                        .HasForeignKey("ServisId")
                        .HasConstraintName("FK_Servis");

                    b.Navigation("Komponenta");

                    b.Navigation("Servis");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.KorisniciUloge", b =>
                {
                    b.HasOne("eWorkshop.Services.Database.Korisnici", "Korisnik")
                        .WithMany("KorisniciUloges")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_KorisnikUloga");

                    b.HasOne("eWorkshop.Services.Database.Uloge", "Uloga")
                        .WithMany("KorisniciUloges")
                        .HasForeignKey("UlogaId")
                        .IsRequired()
                        .HasConstraintName("FK_UlogaKorisnik");

                    b.Navigation("Korisnik");

                    b.Navigation("Uloga");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Magacin", b =>
                {
                    b.HasOne("eWorkshop.Services.Database.Komponente", "Komponenta")
                        .WithMany("Magacins")
                        .HasForeignKey("KomponentaId")
                        .HasConstraintName("FK_Komponenta");

                    b.Navigation("Komponenta");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Servi", b =>
                {
                    b.HasOne("eWorkshop.Services.Database.Korisnici", "Korisnik")
                        .WithMany("Servis")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_KorisnikID");

                    b.HasOne("eWorkshop.Services.Database.RadniZadatak", "RadniZadatak")
                        .WithMany("Servis")
                        .HasForeignKey("RadniZadatakId")
                        .IsRequired()
                        .HasConstraintName("FK_RadniZadatakID");

                    b.HasOne("eWorkshop.Services.Database.Uredjaj", "Uredjaj")
                        .WithMany("Servis")
                        .HasForeignKey("UredjajId")
                        .IsRequired()
                        .HasConstraintName("FK_UredjajID");

                    b.Navigation("Korisnik");

                    b.Navigation("RadniZadatak");

                    b.Navigation("Uredjaj");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Ugovor", b =>
                {
                    b.HasOne("eWorkshop.Services.Database.RadniZadatak", "RadniZadatak")
                        .WithMany("Ugovors")
                        .HasForeignKey("RadniZadatakId")
                        .IsRequired()
                        .HasConstraintName("FK_RadniZadatakUgovor");

                    b.Navigation("RadniZadatak");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Upit", b =>
                {
                    b.HasOne("eWorkshop.Services.Database.Klijenti", "Klijent")
                        .WithMany("Upits")
                        .HasForeignKey("KlijentId")
                        .HasConstraintName("FK_KlijentUpis");

                    b.Navigation("Klijent");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Uredjaj", b =>
                {
                    b.HasOne("eWorkshop.Services.Database.Lokacija", "Lokacija")
                        .WithMany("Uredjajs")
                        .HasForeignKey("LokacijaId")
                        .HasConstraintName("FK__Uredjaj__Lokacij__45F365D3");

                    b.HasOne("eWorkshop.Services.Database.TipUredjaja", "Tip")
                        .WithMany("Uredjajs")
                        .HasForeignKey("TipId")
                        .IsRequired()
                        .HasConstraintName("FK_UredjajTip");

                    b.Navigation("Lokacija");

                    b.Navigation("Tip");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Klijenti", b =>
                {
                    b.Navigation("Upits");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Komponente", b =>
                {
                    b.Navigation("IzvrseniServis");

                    b.Navigation("Magacins");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Korisnici", b =>
                {
                    b.Navigation("KorisniciUloges");

                    b.Navigation("Servis");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Lokacija", b =>
                {
                    b.Navigation("Uredjajs");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.RadniZadatak", b =>
                {
                    b.Navigation("Servis");

                    b.Navigation("Ugovors");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Servi", b =>
                {
                    b.Navigation("IzvrseniServis");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.TipUredjaja", b =>
                {
                    b.Navigation("Uredjajs");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Uloge", b =>
                {
                    b.Navigation("KorisniciUloges");
                });

            modelBuilder.Entity("eWorkshop.Services.Database.Uredjaj", b =>
                {
                    b.Navigation("Servis");
                });
#pragma warning restore 612, 618
        }
    }
}
